"""add chained interval for recurrence

Revision ID: 98159fe895ce
Revises: ade851e4a70f
Create Date: 2020-04-26 18:22:26.112889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98159fe895ce'
down_revision = 'ade851e4a70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'chained')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('chained', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
